name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          
      - run: npm install -g corepack@latest
      - run: corepack enable

      - run: pnpm install

      - run: pnpm --filter @nuxt/devtools-docs lint

      - run: pnpm --filter @nuxt/devtools-docs generate
      
      - run: pnpm --filter @nuxt/devtools-docs typecheck

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-html-preview
          path: .output/public/
          retention-days: 7
